name: YouTube to Podcast

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip
      uses: actions/cache@v3
      with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
         sudo apt update
         sudo apt install ffmpeg -y
         pip install --upgrade pip
         pip install -r requirements.txt

    - name: Download new audio
      env:
        CHANNEL_NAME: ${{ vars.CHANNEL_NAME }}
        CHANNEL_URL: ${{ vars.CHANNEL_URL }}
        COVER_URL: ${{ vars.COVER_URL }}
        OUTPUT_DIR: downloads
        TRACK_FILE: downloaded.txt
        MAX_VIDEOS: 1
      run: python download_audio.py cookies.txt

    - name: Commit & push new audio
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add downloads/ downloaded.txt
        git commit -m "Add new episodes" || echo "No new episodes"
        git push